name: industrial_ci

on:
  push:
    branches:
      - ros1
      - '**-devel'
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.png'
      - 'imgs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'imgs/**'
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  industrial_ci:
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: noetic, ROS_REPO: main, UPSTREAM_WORKSPACE: '.minipupper.repos' }
        experimental: [false]
        include:
          - env: { ROS_DISTRO: noetic, ROS_REPO: testing, UPSTREAM_WORKSPACE: '.minipupper.repos' }
            experimental: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{ matrix.env }}
